name: main

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Store branch name
        run: echo "BUILD_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Store commit hash
        run: echo "BUILD_COMMIT=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Check current date
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d_%H.%M.%S')" >> $GITHUB_ENV
      - name: Generate archive name
        run: echo "BUILD_NAME=${BUILD_BRANCH}_${BUILD_COMMIT}_${BUILD_DATE}_resume_build" >> $GITHUB_ENV

      - name: Print archive name
        run: echo "Archive will be called $BUILD_NAME"

      - name: Install Nix and activate devShell
        uses: purplenoodlesoop/nix-act@v1
        with:
          environment: devShell.x86_64-linux

      - name: Build docs
        run: make

      - name: Archive files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}
          path: bin
